// src/icons.jsx
import {
  FaRegCalendar,
  FaRegCheckCircle,
  FaRegHeart,
  FaBeer,
  FaApple,
  FaArrowAltCircleDown,
  FaArrowAltCircleLeft,
  FaArrowAltCircleRight,
  FaArrowAltCircleUp,
  FaAtom,
  FaBalanceScale,
  FaBicycle,
  FaBitcoin,
  FaBook,
  FaBolt,
  FaBone,
  FaBox,
  FaBriefcase,
  FaBullhorn,
  FaCamera,
  FaCar,
  FaChartBar,
  FaChartLine,
  FaCheckSquare,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaChevronUp,
  FaCloud,
  FaCloudMoon,
  FaCloudSun,
  FaCode,
  FaCogs,
  FaComments,
  FaCookie,
  FaCreditCard,
  FaDesktop,
  FaDog,
  FaDumbbell,
  FaEdit,
  FaEnvelope,
  FaExternalLinkAlt,
  FaFileAlt,
  FaFlag,
  FaFrown,
  FaGamepad,
  FaGuitar,
  FaHamburger,
  FaHandPaper,
  FaHandshake,
  FaHeadphones,
  FaHome,
  FaHospital,
  FaImage,
  FaInfoCircle,
  FaKeyboard,
  FaLeaf,
  FaLightbulb,
  FaLock,
  FaMap,
  FaMobileAlt,
  FaMoon,
  FaMusic,
  FaPalette,
  FaPaperclip,
  FaPaw,
  FaPhone,
  FaPencilAlt,
  FaPlane,
  FaPlayCircle,
  FaPlug,
  FaPlus,
  FaPowerOff,
  FaPrint,
  FaProjectDiagram,
  FaPuzzlePiece,
  FaRedo,
  FaRocket,
  FaSave,
  FaSearch,
  FaSeedling,
  FaServer,
  FaShoppingCart,
  FaSnowflake,
  FaStar,
  FaSun,
  FaSync,
  FaTachometerAlt,
  FaTag,
  FaThumbsUp,
  FaTrophy,
  FaUser,
  FaVolumeUp,
  FaSignInAlt,
  FaSignOutAlt,
  FaThumbsDown,
  FaTrash,
  FaUserAlt,
  FaVideo,
  FaWifi,
} from "react-icons/fa";

// Create an array of icon options
const icons = [
  { id: 1, icon: <FaRegCalendar size={20} />, label: "Calendar" },
  { id: 2, icon: <FaRegCheckCircle size={20} />, label: "Check" },
  { id: 3, icon: <FaRegHeart size={20} />, label: "Heart" },
  { id: 4, icon: <FaBeer size={20} />, label: "Beer" },
  { id: 5, icon: <FaApple size={20} />, label: "Apple" },
  { id: 6, icon: <FaArrowAltCircleDown size={20} />, label: "Arrow Down" },
  { id: 7, icon: <FaArrowAltCircleLeft size={20} />, label: "Arrow Left" },
  { id: 8, icon: <FaArrowAltCircleRight size={20} />, label: "Arrow Right" },
  { id: 9, icon: <FaArrowAltCircleUp size={20} />, label: "Arrow Up" },
  { id: 10, icon: <FaAtom size={20} />, label: "Atom" },
  { id: 11, icon: <FaBalanceScale size={20} />, label: "Balance Scale" },
  { id: 12, icon: <FaBicycle size={20} />, label: "Bicycle" },
  { id: 13, icon: <FaBitcoin size={20} />, label: "Bitcoin" },
  { id: 14, icon: <FaBook size={20} />, label: "Book" },
  { id: 15, icon: <FaBolt size={20} />, label: "Bolt" },
  { id: 16, icon: <FaBone size={20} />, label: "Bone" },
  { id: 17, icon: <FaBox size={20} />, label: "Box" },
  { id: 18, icon: <FaBriefcase size={20} />, label: "Briefcase" },
  { id: 19, icon: <FaBullhorn size={20} />, label: "Bullhorn" },
  { id: 20, icon: <FaCamera size={20} />, label: "Camera" },
  { id: 21, icon: <FaCar size={20} />, label: "Car" },
  { id: 22, icon: <FaChartBar size={20} />, label: "Chart Bar" },
  { id: 23, icon: <FaChartLine size={20} />, label: "Chart Line" },
  { id: 24, icon: <FaCheckSquare size={20} />, label: "Check Square" },
  { id: 25, icon: <FaChevronDown size={20} />, label: "Chevron Down" },
  { id: 26, icon: <FaChevronLeft size={20} />, label: "Chevron Left" },
  { id: 27, icon: <FaChevronRight size={20} />, label: "Chevron Right" },
  { id: 28, icon: <FaChevronUp size={20} />, label: "Chevron Up" },
  { id: 29, icon: <FaCloud size={20} />, label: "Cloud" },
  { id: 30, icon: <FaCloudMoon size={20} />, label: "Cloud Moon" },
  { id: 31, icon: <FaCloudSun size={20} />, label: "Cloud Sun" },
  { id: 32, icon: <FaCode size={20} />, label: "Code" },
  { id: 33, icon: <FaCogs size={20} />, label: "Cogs" },
  { id: 34, icon: <FaComments size={20} />, label: "Comments" },
  { id: 35, icon: <FaCookie size={20} />, label: "Cookie" },
  { id: 36, icon: <FaCreditCard size={20} />, label: "Credit Card" },
  { id: 37, icon: <FaDesktop size={20} />, label: "Desktop" },
  { id: 38, icon: <FaDog size={20} />, label: "Dog" },
  { id: 39, icon: <FaDumbbell size={20} />, label: "Dumbbell" },
  { id: 40, icon: <FaEdit size={20} />, label: "Edit" },
  { id: 41, icon: <FaEnvelope size={20} />, label: "Envelope" },
  { id: 42, icon: <FaExternalLinkAlt size={20} />, label: "External Link" },
  { id: 43, icon: <FaFileAlt size={20} />, label: "File" },
  { id: 44, icon: <FaFlag size={20} />, label: "Flag" },
  { id: 45, icon: <FaFrown size={20} />, label: "Frown" },
  { id: 46, icon: <FaGamepad size={20} />, label: "Gamepad" },
  { id: 47, icon: <FaGuitar size={20} />, label: "Guitar" },
  { id: 48, icon: <FaHamburger size={20} />, label: "Hamburger" },
  { id: 49, icon: <FaHandPaper size={20} />, label: "Hand Paper" },
  { id: 50, icon: <FaHandshake size={20} />, label: "Handshake" },
  { id: 51, icon: <FaHeadphones size={20} />, label: "Headphones" },
  { id: 52, icon: <FaHome size={20} />, label: "Home" },
  { id: 53, icon: <FaHospital size={20} />, label: "Hospital" },
  { id: 54, icon: <FaImage size={20} />, label: "Image" },
  { id: 55, icon: <FaInfoCircle size={20} />, label: "Info" },
  { id: 56, icon: <FaKeyboard size={20} />, label: "Keyboard" },
  { id: 57, icon: <FaLeaf size={20} />, label: "Leaf" },
  { id: 58, icon: <FaLightbulb size={20} />, label: "Lightbulb" },
  { id: 59, icon: <FaLock size={20} />, label: "Lock" },
  { id: 60, icon: <FaMap size={20} />, label: "Map" },
  { id: 61, icon: <FaMobileAlt size={20} />, label: "Mobile" },
  { id: 62, icon: <FaMoon size={20} />, label: "Moon" },
  { id: 63, icon: <FaMusic size={20} />, label: "Music" },
  { id: 64, icon: <FaPalette size={20} />, label: "Palette" },
  { id: 65, icon: <FaPaperclip size={20} />, label: "Paperclip" },
  { id: 66, icon: <FaPaw size={20} />, label: "Paw" },
  { id: 67, icon: <FaPhone size={20} />, label: "Phone" },
  { id: 68, icon: <FaPencilAlt size={20} />, label: "Pencil" },
  { id: 69, icon: <FaPlane size={20} />, label: "Plane" },
  { id: 70, icon: <FaPlayCircle size={20} />, label: "Play Circle" },
  { id: 71, icon: <FaPlug size={20} />, label: "Plug" },
  { id: 72, icon: <FaPlus size={20} />, label: "Plus" },
  { id: 73, icon: <FaPowerOff size={20} />, label: "Power Off" },
  { id: 74, icon: <FaPrint size={20} />, label: "Print" },
  { id: 75, icon: <FaProjectDiagram size={20} />, label: "Project Diagram" },
  { id: 76, icon: <FaPuzzlePiece size={20} />, label: "Puzzle Piece" },
  { id: 77, icon: <FaRedo size={20} />, label: "Redo" },
  { id: 78, icon: <FaRocket size={20} />, label: "Rocket" },
  { id: 79, icon: <FaSave size={20} />, label: "Save" },
  { id: 80, icon: <FaSearch size={20} />, label: "Search" },
  { id: 81, icon: <FaSeedling size={20} />, label: "Seedling" },
  { id: 82, icon: <FaServer size={20} />, label: "Server" },
  { id: 83, icon: <FaShoppingCart size={20} />, label: "Shopping Cart" },
  { id: 84, icon: <FaSignInAlt size={20} />, label: "Sign In" },
  { id: 85, icon: <FaSignOutAlt size={20} />, label: "Sign Out" },
  { id: 86, icon: <FaSnowflake size={20} />, label: "Snowflake" },
  { id: 87, icon: <FaStar size={20} />, label: "Star" },
  { id: 88, icon: <FaSun size={20} />, label: "Sun" },
  { id: 89, icon: <FaSync size={20} />, label: "Sync" },
  { id: 90, icon: <FaTachometerAlt size={20} />, label: "Tachometer" },
  { id: 91, icon: <FaTag size={20} />, label: "Tag" },
  { id: 92, icon: <FaThumbsDown size={20} />, label: "Thumbs Down" },
  { id: 93, icon: <FaThumbsUp size={20} />, label: "Thumbs Up" },
  { id: 94, icon: <FaTrash size={20} />, label: "Trash" },
  { id: 95, icon: <FaTrophy size={20} />, label: "Trophy" },
  { id: 96, icon: <FaUser size={20} />, label: "User" },
  { id: 97, icon: <FaUserAlt size={20} />, label: "User Alt" },
  { id: 98, icon: <FaVideo size={20} />, label: "Video" },
  { id: 99, icon: <FaVolumeUp size={20} />, label: "Volume Up" },
  { id: 100, icon: <FaWifi size={20} />, label: "Wifi" },
];

export default icons;
