const demoData = [
  {
    _id: 1,
    title: "Client Review & Feedback",
    createdAt: new Date(),
    order: 1,
    checked: false,
    category: "2020 goals",
  },
  {
    _id: 2,
    title: "Team Standup Meeting",
    createdAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    order: 2,
    checked: false,
    category: "work",
  },
  {
    _id: 4,
    title: "Design Review Meeting",
    createdAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    order: 3,
    checked: false,
    category: "design",
  },
  {
    _id: 6,
    title: "Quarterly Financial Review",
    createdAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    order: 4,
    checked: false,
    category: "finance",
  },
  {
    _id: 7,
    title: "Client Onboarding Session",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    order: 5,
    checked: false,
    category: "client",
  },
  {
    _id: 9,
    title: "Marketing Campaign Strategy",
    createdAt: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    order: 6,
    checked: true,
    category: "marketing",
  },
  {
    _id: 10,
    title: "Product Launch Meeting",
    createdAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    order: 7,
    checked: false,
    category: "product",
  },
  {
    _id: 11,
    title: "Annual Budget Planning",
    createdAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    order: 8,
    checked: false,
    category: "finance",
  },
  {
    _id: 12,
    title: "User Experience Workshop",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    order: 9,
    checked: true,
    category: "design",
  },
  {
    _id: 13,
    title: "Sales Strategy Meeting",
    createdAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    order: 10,
    checked: false,
    category: "sales",
  },
  {
    _id: 14,
    title: "Client Satisfaction Survey",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    order: 11,
    checked: true,
    category: "client",
  },
];

export default demoData;
